"""Orchestration engine — weekly targets + preferences -> a concrete dated week,
then render it as Markdown (Phase-8-compatible; PDF via pipeline/08_build_pdfs.sh).

Milestone M3 of PRODUCT_ARCHITECTURE.md (§8). Deterministic: no network, no LLM.
Distributes training/recovery sessions across the week and assigns meals per day.
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any

from ..data import venues_for_dish
from ..recommend import meals as meal_lib

_WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

_RUNG_LABEL = {
    "self": "self",
    "cook": "🍳 cook",
    "order": "🛒 order (1-tap hand-off)",
    "book_api": "📅 auto-book",
    "book_handoff": "📅 book (1-tap hand-off)",
    "": "",
}


def _next_monday(d: date) -> date:
    return d + timedelta(days=(7 - d.weekday()) % 7 or 7) if d.weekday() != 0 else d


def _distribute_sessions(targets, n_days: int = 7) -> dict[int, list[dict[str, str]]]:
    """Place training + recovery items onto day indices 0..6. Deterministic."""
    plan: dict[int, list[dict[str, str]]] = {i: [] for i in range(n_days)}

    # Training: spread resistance on Mon/Wed/Fri-ish, Zone-2 mid/late week.
    res = next((it for it in targets.training if "resistance" in it.text), None)
    z2 = next((it for it in targets.training if "Zone-2" in it.text), None)
    if res:
        try:
            count = int(res.text.split("×")[0])
        except ValueError:
            count = 3
        slots = {1: [0], 2: [0, 3], 3: [0, 2, 4], 4: [0, 2, 4, 5]}.get(count, [0, 2, 4])
        for d in slots:
            plan[d].append({"text": "Resistance session (compound-focused)", "rung": "self"})
    if z2:
        plan[5].append({"text": "Zone-2 cardio 40–50 min", "rung": "self"})

    # Recovery: sauna 2× on lower-load days, massage 1× weekend.
    def _venue_meta(it) -> dict[str, str]:
        return {"venue_name": getattr(it, "venue_name", ""),
                "venue_url": getattr(it, "venue_url", ""),
                "venue_address": getattr(it, "venue_address", "")}

    saunas = [it for it in targets.recovery if "sauna" in it.text.lower()]
    if saunas:
        s = saunas[0]
        plan[1].append({"text": "Sauna session", "rung": s.rung, **_venue_meta(s)})
        plan[3].append({"text": "Sauna session", "rung": s.rung, **_venue_meta(s)})
    massage = next((it for it in targets.recovery if "massage" in it.text.lower()), None)
    if massage:
        plan[6].append({"text": "Massage", "rung": massage.rung, **_venue_meta(massage)})

    return plan


def build_week(targets, prefs: dict[str, Any], start: date) -> dict[str, Any]:
    library = meal_lib.filter_meals(prefs.get("diet", {}))
    setattr(targets, "_meals_per_day", prefs.get("diet", {}).get("meals_per_day", 3))
    sessions = _distribute_sessions(targets)

    days = []
    for i in range(7):
        d = start + timedelta(days=i)
        day_meals = meal_lib.select_day(library, targets, i)
        days.append({
            "date": d.isoformat(),
            "weekday": _WEEKDAYS[d.weekday()],
            "meals": day_meals["meals"],
            "totals": day_meals["totals"],
            "protein_ok": day_meals["protein_ok"],
            "sessions": sessions[i],
        })

    return {"start": start.isoformat(), "days": days, "targets": targets, "prefs": prefs}


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def _venue_md(it) -> str:
    if not getattr(it, "venue_name", ""):
        return ""
    if it.venue_url:
        return f"  \n  📍 [{it.venue_name}]({it.venue_url}) · _{it.venue_address}_"
    return f"  \n  📍 {it.venue_name} · _{it.venue_address}_"


def _items_md(items, bullet="-") -> str:
    out = []
    for it in items:
        rung = _RUNG_LABEL.get(it.rung, it.rung)
        tag = f" _({rung})_" if rung and rung != "self" else ""
        why = f" — {it.why}" if it.why else ""
        out.append(f"{bullet} {it.text}{tag}{why}{_venue_md(it)}")
    return "\n".join(out) if out else "_(none)_"


def render_markdown(plan: dict[str, Any], ctx: dict[str, Any]) -> str:
    t = plan["targets"]
    prefs = plan["prefs"]
    city = ctx.get("city", "")
    city_key = city.lower()
    L: list[str] = []

    L.append(f"# Weekly Plan — week of {plan['start']}")
    L.append("")
    L.append(f"_Generated by the Concierge engine from your own data. {city}. "
             f"All numbers are deterministic and traceable. "
             f"**This is information, not medical advice or diagnosis.** "
             f"Supplement doses cited stay within published OTC thresholds; thresholds for "
             f"lipids/vitamins reference ATP III / EFSA / IOM. Discuss anything you want to "
             f"act on with a clinician — especially if you take prescription medication._")
    L.append("")

    # ---- targets summary ----
    L.append("## Targets")
    L.append("")
    L.append(f"- **Energy:** {t.calorie_target_kcal} kcal/day — _{t.calorie_strategy}_  "
             f"(BMR {t.bmr_kcal} via {t.bmr_method} × activity {t.activity_factor} = TDEE {t.tdee_kcal})")
    L.append(f"- **Macros:** protein {t.protein_g} g · fat {t.fat_g} g · carbs {t.carb_g} g  "
             f"(protein {t.protein_g_per_kg} g/kg)")
    L.append("")
    L.append("### Supplements")
    L.append(_items_md(t.supplements))
    L.append("")
    L.append("### Training")
    L.append(_items_md(t.training))
    L.append("")
    L.append("### Recovery")
    L.append(_items_md(t.recovery))
    L.append("")
    if t.behavioral:
        L.append("### This week's behavioural focus")
        L.append(_items_md(t.behavioral))
        L.append("")

    # ---- the week ----
    L.append("## The week")
    L.append("")
    for day in plan["days"]:
        tot = day["totals"]
        flag = "" if day["protein_ok"] else "  ⚠️ _below protein floor — add a snack_"
        L.append(f"### {day['weekday']} {day['date']}")
        L.append(f"**~{tot['kcal']} kcal · P {tot['p']} / C {tot['c']} / F {tot['f']} g**{flag}")
        L.append("")
        for m in day["meals"]:
            rung = _RUNG_LABEL.get(m["rung"], m["rung"])
            L.append(f"- _{m['slot']}_ — {m['name']} "
                     f"(~{m['kcal']} kcal, P{m['p']}/C{m['c']}/F{m['f']}) · {rung}")
            if m["rung"] == "order" and city_key:
                for v in venues_for_dish(m["name"], city_key, limit=2):
                    L.append(f"  - 🔗 [{v['name']}]({v.get('booking_url') or v['url']}) "
                             f"· _{v['neighbourhood']}_ · ~€{v.get('price_est_eur', {}).get('average_main', '')}")
        if day["sessions"]:
            for s in day["sessions"]:
                rung = _RUNG_LABEL.get(s["rung"], s["rung"])
                tag = f" · {rung}" if rung and rung != "self" else ""
                line = f"- 🏋️ {s['text']}{tag}"
                if s.get("venue_name"):
                    line += f"  \n  📍 [{s['venue_name']}]({s['venue_url']}) · _{s['venue_address']}_"
                L.append(line)
        L.append("")

    # ---- screenings (Ornament-style, non-blocking) ----
    L.append("## Tests & screening due (book at your convenience)")
    L.append("")
    L.append(_items_md(t.screenings))
    L.append("")

    # ---- data gaps ----
    if t.data_gaps:
        L.append("## What would sharpen next week's plan")
        L.append("")
        L.append(_items_md(t.data_gaps))
        L.append("")

    # ---- budget tally (rough) ----
    order_meals = sum(1 for d in plan["days"] for m in d["meals"] if m["rung"] == "order")
    bookings = sum(1 for d in plan["days"] for s in d["sessions"])
    L.append("## Approve & pay")
    L.append("")
    L.append(f"- {order_meals} order-meals (1-tap hand-off to your delivery app)")
    L.append(f"- {bookings} session bookings this week")
    budget = prefs.get("budget", {}).get("weekly_eur")
    if budget:
        L.append(f"- Weekly budget cap: €{budget}")
    L.append("- _Nothing is ordered, booked, or charged until you approve. "
             "Money + medical actions always require your confirmation._")
    L.append("")

    L.append("---")
    L.append("_Caveat: meal macros are from a small built-in library — treat as a starting "
             "rotation, not a precise diet. Re-run after connecting a wearable or uploading "
             "new bloods to personalise further._")
    return "\n".join(L) + "\n"
